### ISSUE TITLE
Part_Refiner

### ISSUE THREAD

**Issue by ghost** [Hao-HUST/G2LGAN#2]
Could you upload Part_Refiner file?

**Comment by CRISZJ** [comment]
Could you upload Part_Refiner file?

**Comment by Hao-HUST** [comment]
Sorry for the delay, I have been updated the source code of part refiner.

**Comment by CRISZJ** [comment]
Thanks for your code :)




------------------ 原始邮件 ------------------
发件人: "Hao-HUST"<notifications@github.com>;
发送时间: 2019年9月2日(星期一) 上午8:51
收件人: "Hao-HUST/G2LGAN"<G2LGAN@noreply.github.com>;
抄送：  “SR”<2201444787@qq.com>;“评论”<comment@noreply.github.com>;
主题: Re: [Hao-HUST/G2LGAN] Part_Refiner (#2)




对不起延迟，我已经更新了part refiner的源代码。
  
- 
你收到这个是因为你发表了评论。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。
