### ISSUE TITLE
some issues about input_data dataset

### ISSUE THREAD

**Issue by CRISZJ** [Hao-HUST/G2LGAN#5]
Excuse me, When I download the input_data dataset, I find it is a *.gz file.  When I unzipped this file, I found that there are some attached files. For example, when *.mat is generated, a file with the same name with the prefix name ._ will be generated. I want to ask if I need to delete it. If I don't delete it, run it directly. Value Error: Mat 4 mopt wrong format, byteswapping problem?

**Comment by Hao-HUST** [comment]
All of "._**" files should be deleted if you unzip the "input_data.tar.gz" file on Windows OS, I think such issue is related to my zip operation on Mac OS. 

I will update the input_data file later.

**Comment by CRISZJ** [comment]
And when I finished the running of the file seperate_part_mat.py and gen_pairs.py, I want to run the trian_part file,but there is no file that called Test Data(or'/test/test_chair.npy' )
IOError: [Errno 2] No such file or directory:
/G2LGAN/Part_Refiner/Data_Preparation_for_PR/seperate_result/chair/test/test_chair.npy
