### ISSUE TITLE
The test data about Part Refiner 

### ISSUE THREAD

**Issue by CRISZJ** [Hao-HUST/G2LGAN#6]
When I read your paper, I find you reconstruct a new dataset called test dataset.The part refiner will ues the dataset to trian.So, could you please upload the dataset,if not ,how to create the datastet? 
Thanks for your reading. :  )

**Comment by Hao-HUST** [comment]
The '/test/test_chair.npy' file is used to test the performance of PR during training, but such file is not a necessary part for training PR, so I modified the "train_part_refiner.py" and you can run it without '/test/test_chair.npy' file.

I asked my friend to check the '/test/test_chair.npy' file and will upload it if he finds it.

**Comment by CRISZJ** [comment]
Thanks for your review, When I run the train_part_refiner.py,I meet the problem that called:
IOError: [Errno 2] No such file or directory: '/G2LGAN/Part_Refiner/Data_Preparation_for_PR/seperate_result/chair/test/test_chair.npy'
so,could you please tell me how to sovle it?Do all the code related to this place need to be deleted?

**Comment by Hao-HUST** [comment]
Yes, as I said, the test_chair.npy file is used to visualize the performance of PR during training, it is not the necessary part for training PR. After training is done, you can use the pre-trained model of PR to refine the generated initial shapes from G2LGAN and visualize the final shape results, same as test_chair.npy file.

You can run the modified G2LGAN/Part Refiner/train_part_refiner.py script to train the PR.

**Comment by CRISZJ** [comment]
OK, thanks very much for your review again!!!

**Comment by Hao-HUST** [comment]
If you need more discussion about this issue, I will reopen it again.
