### ISSUE TITLE
About the tool of visual tool

### ISSUE THREAD

**Issue by CRISZJ** [Hao-HUST/G2LGAN#7]
Thanks for providing two different visual tools, .mat  and .npy. But I can only use the .npy tool.When   I use the tool of .mat, it can not read the file of .mat.Could you please tell me how to use it?I am very interesed about it.    :-)

**Comment by Hao-HUST** [comment]
The Visualization Tool for .mat file can be run on my environment, can you describe your problem more clearly? 

If you want to visualize a specific .mat file, you need to click "Openone" button and select the mat file; If you want to visualize all .mat files on a folder, you need to use the "Open" button and select the folder path.

**Comment by CRISZJ** [comment]
Thanks for your review again.I want to visualize the gen_32 data in the input_data dataset, which is the .mat data, so I used the visual .mat tool to run, but when I click open and open gen_32, I find that the reality is an empty file, and the page is There are no realistically readable files. By the way,I would like to ask, will the network input model strictly accept the resolution? If the initial model resolution is very high, what is the time complexity and memory usage?
