### ISSUE TITLE
visualization.

### ISSUE THREAD

**Issue by CRISZJ** [Hao-HUST/G2LGAN#8]
Thanks for your review again.I want to visualize the gen_32 data in the input_data dataset, which is the .mat data, so I used the visual .mat tool to run, but when I click open and open gen_32, I find that the reality is an empty file, and the page is There are no realistically readable files. By the way,I would like to ask, will the network input model strictly accept the resolution? If the initial model resolution is very high, what is the time complexity and memory usage?

**Comment by Hao-HUST** [comment]
Sorry for delaying. Please let me answer your questions one by one:

1. According to your description, it is hard to figure out what happened, so it is helpful for me if you can share your gen_32 file.
2. Currently, the networks strictly accept the shape resolution, the G2LGAN generates 32^3 voxel shape and the PR then refines it from 32^3 to 64^3.  I do not suggest to improve the generated shape resolution, it will occupy too much GPU memory and make the generation harder. The voxel shape representation is too sparse, it means that most of the voxel is empty if you improve the voxel resolution to 128 or higher, Octree CNN or similar methods try to solve such problem. Frankly speaking, compare to voxel representation, the point cloud representation is more efficient, but point cloud based shape generation is much harder then voxel-based method.
